### ISSUE TITLE
网页加载太慢了

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaCopilotDesigner#10]
这还是在有缓存的情况下，prts.plus 的加载时间

![image](https://user-images.githubusercontent.com/18511905/176835732-72be9c11-473a-4d99-96ca-119e80d2aaa2.png)

**Comment by MistEO** [comment]
换个浏览器，没有缓存的情况下

![image](https://user-images.githubusercontent.com/18511905/176836104-2803e3ab-fb46-49c5-9a83-9bc4eeedfe7b.png)

**Comment by Shawnsdaddy** [comment]
@MistEO 我能修复2个404（耗时1.5s的那个）错误，剩下的就是服务器问题了

**Comment by MistEO** [comment]
> @MistEO 我能修复2个404（耗时1.5s/ 3s的那个）错误，剩下的就是服务器问题了

那就很可以了

这样的话或者这个 issue 应该改成 bug
