### ISSUE TITLE
希望不登陆用户也可以点赞

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaCopilotDesigner#14]
哪有那么多恶意刷赞的（）

**Comment by LiamSho** [comment]
你好，有的，已经有恶意流量了（

**Comment by MistEO** [comment]
> 你好，有的，已经有恶意流量了（

恶意流量是一码事；恶意刷赞他要真想刷，不停的注册账号不是一样的么（

**Comment by LiamSho** [comment]
那不一样，注册账号我知道是谁干的，没注册匿名的连是谁都不知道（

点赞不追踪是谁干的就很扯（

**Comment by MistEO** [comment]
讨论了一下不太行，那关了）
