### ISSUE TITLE
MAA升级后无法使用作业制作器

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaCopilotDesigner#5]
在4.0.0版本OTA升级到4.0.1版本后，“自动战斗作业制作器”与“自动战斗作业生成器-v1.0”均无法正常使用。
“自动战斗作业制作器”可以填写关卡名、标题、描述。下载载入JSON、添加群组、新增干员、新增流程等按键均无法使用。
“自动战斗作业生成器-v1.0”可以填写关卡名、标题、描述、使用载入JSON（读取后无反应）。下载JSON、新增干员、新增流程等按键均无法使用。
（使用Edge浏览器，版本 103.0.1264.37 (正式版本) (64 位)。MAA路径均为英文）
[以下为错误显示]
![自动战斗作业制作器](https://user-images.githubusercontent.com/73384329/175823042-f2f62b02-990d-4777-9fc5-dbde15a0cf13.PNG)
![自动战斗作业生成器-v1 0](https://user-images.githubusercontent.com/73384329/175823044-d78a7ae8-9a39-4394-9542-15e8bb2d291a.PNG)

**Comment by Shawnsdaddy** [comment]
请使用网页版 脱机版本已经不再维护。谢谢

[网址](https://www.prts.plus/)
